### ISSUE TITLE
Why does low level header include wpilibc headers?

### ISSUE THREAD

**Issue by virtuald** [Digilent/dmc60c-frc-api#1]
[Specifically](https://github.com/Digilent/dmc60c-frc-api/blob/c0b3972b30408bd417cbe043b0fa762ee36e65f6/include/digilent/dmc60/DMC60C_C.h#L3):

```
#include "MotorSafetyHelper.h"
#include "MotorSafety.h"
#include "ErrorBase.h"
```

**Comment by tom21091** [comment]
Yeah, I'm currently rewriting the library to conform better with WPIlib. These are being removed in the next public release.
