### ISSUE TITLE
Bug - 10 or More Devices Causes Web Server Page Fault - Web Server UI

### ISSUE THREAD

**Issue by Sn3akyP3t3** [Digilent/dmc60c-frc-api#11]
I'm sorry if these bugs I've been reporting don't belong in this space, but they need to be reported.  This is the last one I believe.  We ran into a wide variety of problems with the Digilent DMC60C mostly stemming from hardware QA issues which forced us to abandon this product since it seems unstable and extremely high maintenance with troubleshooting and working through the CAN web server UI flaky behavior.

What we witnessed is that when firing up the RoboRIO with 10+ DMC60C units it begins to load the web page and when 10 units are showing up adding one more has shown to degrade the page to a white classic error page in all 3 of the major browsers Firefox, Chrome, and Edge.

At this time I'm no longer willing to continue troubleshooting any issues.  I hope these bug reports do end up getting looked into and that the hardware QA issues that my team will be reporting via RMA on phone will be addressed for future revisions.  Unrelated to this bug, but worthy noting for other teams is that we discovered 2x of 12 units had their CAN wires internally separated from their copper traces on the PCB rendering them dead on arrival.  The wires that enter and leave the internals of the unit are not adequately fixed to the body of the structure allowing external forces on the wire to act directly on the solder joints.  We also observed that the screws holding the case closed seemed slightly loose which probably didn't help the wire fixed to body issue either.  Lastly, we had one unit that was flashing green on power-up.  After troubleshooting what that meant we found it was stuck in calibration mode.  The cause was that the center button silicone rubber was mashed up against the button on the inside likely something accidentally done during assembly.  When we released that tension off that button the unit started reporting in with CAN ID of 0, but then quickly met the web error load page so it couldn't be talked to anyway.

With all the issues we've experienced with this product we can't confidently use them to compete with.  Hopefully the QA issues can be worked out and we may return in future years to try again, but this time with a smaller number of units to build back confidence before going whole enchilada.

**Comment by tom21091** [comment]
Hi Sn3akyP3t3, I really appreciate all of the feedback you've sent us. We are doing all we can to get these bugs fixed as soon as we can. I'm sorry that you had such a tough time with the DMC60C. This is a new field for us, so it's a bit of a learning experience. Once again, thank you for taking the time to give us as much feedback as you did.
