### ISSUE TITLE
Missing Linux x86-64 libraries

### ISSUE THREAD

**Issue by auscompgeek** [Digilent/dmc60c-frc-api#12]
Your vendor JSON declares the availability of Linux x86-64 binaries. However, they are nowhere to be found in the Maven repo.

**Comment by OpethMC** [comment]
How do I access the C api? I see function prototypes in the headers but not the source code for the functions.

**Comment by tom21091** [comment]
Hi auscompgeek, that is a typo. We'll remove that from the json in the next release.

**Comment by tom21091** [comment]
Hi OpethMC, the C API is a wrapper API for the CPP API. The source is found at the bottom of DMC60C.cpp

**Comment by OpethMC** [comment]
Thanks @tom21091, where is the file DMC60C.cpp located? Do you think it should be possible to use the C wrapper and CPP API to communicate over CAN to the dmc60c? I am using the TMS570LC4357 processor from texas instruments and I'm interested in sending PWM commands to the dmc60c (which I've managed to do) while also using CAN messages to read the current, voltage, and any fault data.

**Comment by tom21091** [comment]
Hi @OpethMC. No, it won't be possible with this API. This API is designed specifically for FRC and the roboRIO running Linux. The low-level sources you need are closed source by request from FIRST. However, we do have a CAN protocol guide on our [wiki](https://reference.digilentinc.com/dmc-60c/start). If you have further questions, you should use our [support forum](https://forum.digilentinc.com/) to ask them.

Thanks!
