### ISSUE TITLE
getClosedLoopError return type mismatch

### ISSUE THREAD

**Issue by auscompgeek** [Digilent/dmc60c-frc-api#3]
The `DMC60C::getClosedLoopError()` method returns a `double`:

https://github.com/Digilent/dmc60c-frc-api/blob/1209d162becf450b10e53f076f924b834a80bc1f/include/digilent/dmc60/DMC60C.h#L261-L267

but the `c_DMC60C_getClosedLoopError` function returns a `float`:

https://github.com/Digilent/dmc60c-frc-api/blob/1209d162becf450b10e53f076f924b834a80bc1f/include/digilent/dmc60/DMC60C_C.h#L42

Is this intentional?

I also noticed the corresponding Java method seems to return nothing too...

**Comment by tom21091** [comment]
Thanks for spotting this. This wasn't intentional, I've uploaded the fix.
