### ISSUE TITLE
LabView - Better Location For Example Projects

### ISSUE THREAD

**Issue by Sn3akyP3t3** [Digilent/dmc60c-frc-api#4]
LabView has a very awesome place to search and open example projects. It would be great if your examples could be found there as well. Maybe they should exist in both places for the time being, but I think it could just as easily be moved to the easier to find searchable location.

![52528392-63f80200-2ca3-11e9-835f-55b262f27847](https://user-images.githubusercontent.com/1790256/52528618-7aed2300-2ca8-11e9-8993-9388095d4005.png)

**Comment by tom21091** [comment]
Thanks for the suggestion, I've made these changes in the latest push.
