### ISSUE TITLE
Cannot Build Example - Lack of Permission

### ISSUE THREAD

**Issue by Sn3akyP3t3** [Digilent/dmc60c-frc-api#5]
After getting started with an example it was discovered that the example will not build due to lack of some sort of permissions.  It appears that another user's computer was left somehow in the project file as a path?  Not sure, its not someone on either of our machines that this failed on.

```
Click the link below to visit the Application Builder support page. Use the following information as a reference:

Error 8 occurred at Create Folder in Create Directory Recursive.vi->AB_Destination.lvclass:Create_Destination.vi->AB_Build.lvclass:Create_Destinations.vi->AB_Application.lvclass:Create_Destinations.vi->AB_Build.lvclass:Build.vi->AB_Application.lvclass:Build.vi->AB_RTEXE.lvclass:Build.vi->AB_Engine_Build.vi->AB_Build_Invoke.vi->AB_Build_Invoke.vi.ProxyCaller

Possible reason(s):

LabVIEW: (Hex 0x8) File permission error. You do not have the correct permissions for the file.

C:\Users\tkappenm
```

Build was kicked off from here:
![image](https://user-images.githubusercontent.com/1790256/52528695-36628700-2caa-11e9-9a31-a5ee0efc0947.png)

**Comment by tom21091** [comment]
Thanks for bringing this up. I've changed the local destination directory to Public\Documents instead of tkappenm\Documents. Labview doesn't allow relative paths here, so hopefully this fixes the issue.
Changes are in the latest push.
